# Generated by Django 4.2.23 on 2025-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
