# Generated by Django 5.2.5 on 2025-08-15 14:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 15, 14, 13, 5, 138264, tzinfo=datetime.timezone.utc))]),
        ),
    ]
