# Generated by Django 5.2.5 on 2025-08-15 17:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 15, 17, 59, 46, 669114, tzinfo=datetime.timezone.utc))]),
        ),
    ]
