# Generated by Django 5.2.5 on 2025-08-15 18:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 15, 18, 14, 55, 492199, tzinfo=datetime.timezone.utc))]),
        ),
    ]
