# Generated by Django 5.2.5 on 2025-08-13 16:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 13, 16, 32, 0, 364156, tzinfo=datetime.timezone.utc))]),
        ),
    ]
