# Generated by Django 5.2.5 on 2025-08-16 00:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 16, 0, 8, 35, 876435, tzinfo=datetime.timezone.utc))]),
        ),
    ]
