# Generated by Django 5.2.5 on 2025-08-21 12:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 8, 21, 12, 18, 57, 722498, tzinfo=datetime.timezone.utc))]),
        ),
    ]
